export default function DataSources() {
  return <main id="main-content" className="shell sources-page"><header><p className="eyebrow">OPEN DATA / TRANSPARENT EVIDENCE</p><h1>Know your sources.</h1><p>SatQuery retrieves observations from public services. Coverage, cloud conditions and provider availability determine what can be returned.</p></header>
    <div className="feature-grid">
      <article className="card"><h2>Sentinel-2</h2><p>Optical imagery and vegetation context, with cloud screening and calibrated reflectance. Native RGB sampling is 10 metres; enlarging an image adds no observed detail.</p><a href="https://planetarycomputer.microsoft.com/dataset/sentinel-2-l2a" target="_blank" rel="noreferrer">Explore source ↗</a></article>
      <article className="card"><h2>Sentinel-1 RTC</h2><p>Calibrated radar backscatter for complementary observations. Crop retrieval keeps the same radar track within each season. Access depends on provider availability.</p><a href="https://planetarycomputer.microsoft.com/dataset/sentinel-1-rtc" target="_blank" rel="noreferrer">Explore source ↗</a></article>
      <article className="card"><h2>NASA POWER</h2><p>Public daily rainfall and temperature data. This is gridded weather at the selected point, not a measurement from a field station. No API key is required by this integration.</p><a href="https://power.larc.nasa.gov/" target="_blank" rel="noreferrer">Explore source ↗</a></article>
      <article className="card"><h2>India OGD</h2><p>Official district crop statistics when a verified resource is configured by the server operator. Requires an OGD key, resource ID and verified units. District statistics are context, not field-level yield predictions.</p><a href="https://www.data.gov.in/catalog/district-wise-season-wise-crop-production-statistics-0" target="_blank" rel="noreferrer">Explore catalogue ↗</a></article>
    </div><section className="card"><h2>From question to evidence</h2><ol><li>Open one of the four analysis tools and select your region.</li><li>Choose dates and the required task details, then retrieve observations.</li><li>Check source dates, coverage and limitations before interpreting the result.</li><li>Export results with their source provenance.</li></ol><p>Crop Outlook retrieves context automatically. A production yield forecast requires a validated crop-specific model; the research tool is separate.</p></section>
  </main>;
}
